import { jsPDF } from "jspdf";

interface ItineraryDay {
  day: string;
  city: string;
  morning: string;
  afternoon: string;
  evening: string;
  accommodation: string;
  meals: string;
  estimated_cost: string;
}

interface TravelPlan {
  itinerary: ItineraryDay[];
  total_estimated_cost: string;
  travel_tips: string[];
  packing_list: string[];
  emergency_contacts: {
    local_emergency: string;
    embassy: string;
    hotel: string;
  };
}

interface AcceptedTripData {
  plan: TravelPlan;
  summary: string;
  destinations: string[];
  startDate: string;
  endDate: string;
  budget: string;
  accommodation: string;
  transportation: string;
  interests?: string[];
  acceptedAt?: string;
}

export function exportItineraryToPDF(trip: AcceptedTripData) {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPageBreak = (neededSpace = 25) => {
    if (y + neededSpace > pageHeight - margin) {
      doc.addPage();
      y = margin;
      drawHeaderFooter();
    }
  };

  const drawHeaderFooter = () => {
    // Top subtle bar
    doc.setFillColor(72, 92, 17); // #485C11
    doc.rect(0, 0, pageWidth, 4, "F");

    // Footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(140, 140, 140);
    doc.text(
      "Generated by Roamly — AI Travel Intelligence • www.roamly.travel",
      margin,
      pageHeight - 8
    );
  };

  drawHeaderFooter();

  // 1. MAIN HEADER / BRANDING
  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(72, 92, 17);
  doc.text("ROAMLY", margin, y);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(107, 127, 58);
  doc.text("AI TRAVEL PLANNER • OFFICIAL ITINERARY", margin + 42, y - 1);

  y += 4;
  doc.setDrawColor(229, 231, 219);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentWidth, y);
  y += 8;

  // 2. TRIP TITLE & OVERVIEW BOX
  const tripTitle = trip.destinations?.length > 0 ? trip.destinations.join(" • ") : "Custom Travel Plan";
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(26, 26, 26);
  doc.text(tripTitle, margin, y);
  y += 6;

  // Info Card Box
  doc.setFillColor(248, 251, 245);
  doc.setDrawColor(220, 230, 205);
  doc.roundedRect(margin, y, contentWidth, 24, 3, 3, "FD");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(70, 70, 70);

  // Row 1
  doc.text(`Dates: ${trip.startDate || "N/A"} to ${trip.endDate || "N/A"}`, margin + 5, y + 7);
  doc.text(`Budget Tier: ${trip.budget || "Mid-range"}`, margin + 65, y + 7);
  doc.text(`Total Cost Est: ${trip.plan.total_estimated_cost || "N/A"}`, margin + 120, y + 7);

  // Row 2
  doc.text(`Stay: ${trip.accommodation || "Hotel"}`, margin + 5, y + 15);
  doc.text(`Transport: ${trip.transportation || "Train/Flight"}`, margin + 65, y + 15);
  if (trip.interests && trip.interests.length > 0) {
    const interestsStr = trip.interests.slice(0, 3).join(", ") + (trip.interests.length > 3 ? ` +${trip.interests.length - 3}` : "");
    doc.text(`Interests: ${interestsStr}`, margin + 120, y + 15);
  }

  y += 32;

  // 3. TRIP SUMMARY
  if (trip.summary) {
    checkPageBreak(25);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(72, 92, 17);
    doc.text("Trip Summary & Highlights", margin, y);
    y += 5;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const summaryLines = doc.splitTextToSize(trip.summary, contentWidth);
    doc.text(summaryLines, margin, y);
    y += summaryLines.length * 4.5 + 6;
  }

  // 4. DAY-BY-DAY ITINERARY
  checkPageBreak(25);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(72, 92, 17);
  doc.text("Day-by-Day Detailed Schedule", margin, y);
  y += 6;

  (trip.plan.itinerary || []).forEach((day, index) => {
    checkPageBreak(45);

    // Day Header
    doc.setFillColor(240, 245, 230);
    doc.roundedRect(margin, y, contentWidth, 8, 2, 2, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(54, 74, 14);
    doc.text(`${day.day} — ${day.city}`, margin + 4, y + 5.5);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(72, 92, 17);
    doc.text(`Est: ${day.estimated_cost}`, margin + contentWidth - 25, y + 5.5);

    y += 12;

    // Morning, Afternoon, Evening
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(180, 100, 20); // Morning amber
    doc.text("• MORNING: ", margin + 3, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    const morningLines = doc.splitTextToSize(day.morning || "Free exploration", contentWidth - 25);
    doc.text(morningLines, margin + 25, y);
    y += morningLines.length * 4.2 + 2;

    checkPageBreak(25);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(30, 100, 180); // Afternoon blue
    doc.text("• AFTERNOON: ", margin + 3, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    const aftLines = doc.splitTextToSize(day.afternoon || "Sightseeing and leisure", contentWidth - 30);
    doc.text(aftLines, margin + 30, y);
    y += aftLines.length * 4.2 + 2;

    checkPageBreak(25);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(80, 50, 150); // Evening indigo
    doc.text("• EVENING: ", margin + 3, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40, 40, 40);
    const eveLines = doc.splitTextToSize(day.evening || "Dinner and evening walk", contentWidth - 25);
    doc.text(eveLines, margin + 25, y);
    y += eveLines.length * 4.2 + 2;

    // Stay and Meals
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text(`Stay: ${day.accommodation || "Hotel"}  |  Meals: ${day.meals || "Local dining"}`, margin + 3, y);
    y += 7;

    doc.setDrawColor(235, 235, 230);
    doc.line(margin, y, margin + contentWidth, y);
    y += 5;
  });

  // 5. TRAVEL TIPS & PACKING
  if (trip.plan.travel_tips?.length > 0 || trip.plan.packing_list?.length > 0) {
    checkPageBreak(35);
    y += 3;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(72, 92, 17);
    doc.text("Travel Tips & Recommended Packing", margin, y);
    y += 6;

    if (trip.plan.travel_tips?.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      doc.text("Tips:", margin + 2, y);
      y += 4.5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(60, 60, 60);
      trip.plan.travel_tips.slice(0, 4).forEach((tip) => {
        checkPageBreak(10);
        const tipLines = doc.splitTextToSize(`• ${tip}`, contentWidth - 6);
        doc.text(tipLines, margin + 5, y);
        y += tipLines.length * 4;
      });
      y += 2;
    }

    if (trip.plan.packing_list?.length > 0) {
      checkPageBreak(25);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(50, 50, 50);
      doc.text("Packing Checklist:", margin + 2, y);
      y += 4.5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(60, 60, 60);
      trip.plan.packing_list.slice(0, 4).forEach((item) => {
        checkPageBreak(10);
        doc.text(`[ ] ${item}`, margin + 5, y);
        y += 4;
      });
      y += 3;
    }
  }

  // 6. EMERGENCY CONTACTS
  if (trip.plan.emergency_contacts) {
    checkPageBreak(25);
    doc.setFillColor(254, 242, 242);
    doc.setDrawColor(254, 202, 202);
    doc.roundedRect(margin, y, contentWidth, 16, 2, 2, "FD");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(8.5);
    doc.setTextColor(185, 28, 28);
    doc.text("Emergency Contacts", margin + 4, y + 5);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(70, 70, 70);
    const emg = trip.plan.emergency_contacts;
    doc.text(`Emergency: ${emg.local_emergency || "112"}`, margin + 4, y + 11);
    doc.text(`Tourist Helpline: ${emg.embassy || "1363"}`, margin + 65, y + 11);
    doc.text(`Hotel Desk: ${emg.hotel || "Hotel Reception"}`, margin + 125, y + 11);
  }

  // Save PDF file
  const fileName = `Roamly_Itinerary_${(trip.destinations?.[0] || "Trip").replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;
  doc.save(fileName);
}
